# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrafficlqNeen.ui'
##
## Created by: Qt User Interface Compiler version 5.15.8
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore


class Ui_Interface(object):
    def setupUi(self, Interface):
        if not Interface.objectName():
            Interface.setObjectName(u"Interface")
        Interface.setWindowModality(Qt.ApplicationModal)
        Interface.resize(1464, 679)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Interface.sizePolicy().hasHeightForWidth())
        Interface.setSizePolicy(sizePolicy)
        Interface.setMinimumSize(QSize(40, 40))
        Interface.setMaximumSize(QSize(500000, 5000000))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(46, 66, 140, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        brush2 = QBrush(QColor(25, 33, 71, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(36, 31, 49, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush5 = QBrush(QColor(255, 255, 220, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        Interface.setPalette(palette)
        font = QFont()
        font.setFamily(u"Liberation Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QFont.PreferDefault)
        Interface.setFont(font)
        Interface.setLayoutDirection(Qt.LeftToRight)
        Interface.setAutoFillBackground(False)
        Interface.setStyleSheet(u"\n"
"                color: rgb(255, 255, 255);\n"
"            ")
        Interface.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        Interface.setAnimated(False)
        Interface.setDocumentMode(True)
        Interface.setTabShape(QTabWidget.Triangular)
        Interface.setDockNestingEnabled(False)
        self.actionOpen = QAction(Interface)
        self.actionOpen.setObjectName(u"actionOpen")
        font1 = QFont()
        self.actionOpen.setFont(font1)
        self.actionRecent = QAction(Interface)
        self.actionRecent.setObjectName(u"actionRecent")
        self.actionSave = QAction(Interface)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(Interface)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionPrint = QAction(Interface)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionClose = QAction(Interface)
        self.actionClose.setObjectName(u"actionClose")
        self.actionExit = QAction(Interface)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(Interface)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionCut = QAction(Interface)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(Interface)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(Interface)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelect = QAction(Interface)
        self.actionSelect.setObjectName(u"actionSelect")
        self.actionSelect_All = QAction(Interface)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionTheme = QAction(Interface)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionZoom_in = QAction(Interface)
        self.actionZoom_in.setObjectName(u"actionZoom_in")
        self.actionZoom_out = QAction(Interface)
        self.actionZoom_out.setObjectName(u"actionZoom_out")
        self.actionFont = QAction(Interface)
        self.actionFont.setObjectName(u"actionFont")
        self.actionPrefrences = QAction(Interface)
        self.actionPrefrences.setObjectName(u"actionPrefrences")
        font2 = QFont()
        font2.setKerning(False)
        self.actionPrefrences.setFont(font2)
        self.actionAbout = QAction(Interface)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionDark_Light_Mode = QAction(Interface)
        self.actionDark_Light_Mode.setObjectName(u"actionDark_Light_Mode")
        self.centralwidget = QWidget(Interface)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(True)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QTabWidget.South)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.tab_1.setAutoFillBackground(True)
        self.verticalLayout_3 = QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.tableWidget_2 = QTableWidget(self.tab_1)
        if (self.tableWidget_2.columnCount() < 14):
            self.tableWidget_2.setColumnCount(14)
        font3 = QFont()
        font3.setPointSize(9)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font3);
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem)
        font4 = QFont()
        font4.setPointSize(10)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        font5 = QFont()
        font5.setPointSize(9)
        font5.setKerning(True)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setText(u"Destenation Port");
        __qtablewidgetitem5.setFont(font5);
        self.tableWidget_2.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setFont(font4);
        self.tableWidget_2.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(False)
        font6.setWeight(50)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setFont(font6);
        self.tableWidget_2.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        font7 = QFont()
        font7.setFamily(u"Cantarell")
        font7.setPointSize(11)
        font7.setBold(False)
        font7.setWeight(50)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setFont(font7);
        self.tableWidget_2.setHorizontalHeaderItem(11, __qtablewidgetitem11)
        font8 = QFont()
        font8.setFamily(u"Cantarell")
        font8.setPointSize(11)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setFont(font8);
        self.tableWidget_2.setHorizontalHeaderItem(12, __qtablewidgetitem12)
        if (self.tableWidget_2.rowCount() < 4):
            self.tableWidget_2.setRowCount(4)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setFont(font3);
        self.tableWidget_2.setItem(0, 5, __qtablewidgetitem13)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy1)
        self.tableWidget_2.setMinimumSize(QSize(500, 500))
        self.tableWidget_2.setTabletTracking(True)
        self.tableWidget_2.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_2.setAutoFillBackground(True)
        self.tableWidget_2.setStyleSheet(u"background-color: rgb(25, 33, 71);\n"
"                                                color: rgb(255, 255, 255);\n"
"                                                gridline-color: rgb(119, 118, 123);\n"
"                                            ")
        self.tableWidget_2.setFrameShape(QFrame.StyledPanel)
        self.tableWidget_2.setFrameShadow(QFrame.Sunken)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setAutoScrollMargin(14)
        self.tableWidget_2.setProperty("showDropIndicator", False)
        self.tableWidget_2.setDragDropOverwriteMode(False)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.ContiguousSelection)
        self.tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_2.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setGridStyle(Qt.CustomDashLine)
        self.tableWidget_2.setSortingEnabled(True)
        self.tableWidget_2.setRowCount(4)
        self.tableWidget_2.setColumnCount(14)
        self.tableWidget_2.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setStretchLastSection(True)

        self.verticalLayout_3.addWidget(self.tableWidget_2)

        self.BackButton_2 = QPushButton(self.tab_1)
        self.BackButton_2.setObjectName(u"BackButton_2")
        self.BackButton_2.setEnabled(True)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.BackButton_2.setPalette(palette1)
        self.BackButton_2.setStyleSheet(u"")

        self.verticalLayout_3.addWidget(self.BackButton_2)

        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setAutoFillBackground(True)
        self.verticalLayout_2 = QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tableWidget = QTableWidget(self.tab_2)
        if (self.tableWidget.columnCount() < 8):
            self.tableWidget.setColumnCount(8)
        __qtablewidgetitem14 = QTableWidgetItem()
        __qtablewidgetitem14.setFont(font3);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        __qtablewidgetitem15.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        __qtablewidgetitem16.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        __qtablewidgetitem18.setFont(font6);
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        __qtablewidgetitem20.setFont(font8);
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem20)
        if (self.tableWidget.rowCount() < 4):
            self.tableWidget.setRowCount(4)
        self.tableWidget.setObjectName(u"tableWidget")
        sizePolicy1.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy1)
        self.tableWidget.setTabletTracking(True)
        self.tableWidget.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet(u"background-color: rgb(25, 33, 71);\n"
"                                                color: rgb(255, 255, 255);\n"
"                                                gridline-color: rgb(119, 118, 123);\n"
"                                            ")
        self.tableWidget.setFrameShape(QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(14)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QAbstractItemView.ContiguousSelection)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(Qt.CustomDashLine)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)

        self.verticalLayout_2.addWidget(self.tableWidget)

        self.BackButton = QPushButton(self.tab_2)
        self.BackButton.setObjectName(u"BackButton")
        self.BackButton.setEnabled(True)
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.BackButton.setPalette(palette2)
        self.BackButton.setStyleSheet(u"")

        self.verticalLayout_2.addWidget(self.BackButton)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayout_4 = QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.tableWidget_3 = QTableWidget(self.tab_3)
        if (self.tableWidget_3.columnCount() < 8):
            self.tableWidget_3.setColumnCount(8)
        __qtablewidgetitem21 = QTableWidgetItem()
        __qtablewidgetitem21.setFont(font3);
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        __qtablewidgetitem22.setFont(font4);
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        __qtablewidgetitem23.setFont(font4);
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        __qtablewidgetitem24.setFont(font4);
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        __qtablewidgetitem25.setFont(font6);
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        __qtablewidgetitem27.setFont(font8);
        self.tableWidget_3.setHorizontalHeaderItem(6, __qtablewidgetitem27)
        if (self.tableWidget_3.rowCount() < 4):
            self.tableWidget_3.setRowCount(4)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        sizePolicy1.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy1)
        self.tableWidget_3.setTabletTracking(True)
        self.tableWidget_3.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_3.setAutoFillBackground(True)
        self.tableWidget_3.setStyleSheet(u"background-color: rgb(25, 33, 71);\n"
"                                                color: rgb(255, 255, 255);\n"
"                                                gridline-color: rgb(119, 118, 123);\n"
"                                            ")
        self.tableWidget_3.setFrameShape(QFrame.StyledPanel)
        self.tableWidget_3.setFrameShadow(QFrame.Sunken)
        self.tableWidget_3.setLineWidth(1)
        self.tableWidget_3.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_3.setAutoScroll(True)
        self.tableWidget_3.setAutoScrollMargin(14)
        self.tableWidget_3.setProperty("showDropIndicator", False)
        self.tableWidget_3.setDragDropOverwriteMode(False)
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setSelectionMode(QAbstractItemView.ContiguousSelection)
        self.tableWidget_3.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_3.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_3.setGridStyle(Qt.CustomDashLine)
        self.tableWidget_3.setSortingEnabled(True)
        self.tableWidget_3.setRowCount(4)
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setStretchLastSection(True)

        self.verticalLayout_4.addWidget(self.tableWidget_3)

        self.BackButton_3 = QPushButton(self.tab_3)
        self.BackButton_3.setObjectName(u"BackButton_3")
        self.BackButton_3.setEnabled(True)
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.BackButton_3.setPalette(palette3)
        self.BackButton_3.setStyleSheet(u"")

        self.verticalLayout_4.addWidget(self.BackButton_3)

        self.tabWidget.addTab(self.tab_3, "")

        self.verticalLayout.addWidget(self.tabWidget)

        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Interface)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1464, 25))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setMinimumSize(QSize(400, 400))
        font9 = QFont()
        font9.setFamily(u"Cantarell")
        font9.setBold(False)
        font9.setItalic(False)
        font9.setWeight(50)
        self.menuFile.setFont(font9)
        self.menuFile.setTearOffEnabled(True)
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        Interface.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionPrefrences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionDark_Light_Mode)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionFont)

        self.retranslateUi(Interface)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Interface)
    # setupUi

    def retranslateUi(self, Interface):
        Interface.setWindowTitle(QCoreApplication.translate("Interface", u"Network Traffic Analyzer", None))
        self.actionOpen.setText(QCoreApplication.translate("Interface", u"Open...", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("Interface", u"Open Pcap FIle", None))
#endif // QT_CONFIG(tooltip)
        self.actionRecent.setText(QCoreApplication.translate("Interface", u"Recent", None))
        self.actionSave.setText(QCoreApplication.translate("Interface", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("Interface", u"Save as...", None))
        self.actionPrint.setText(QCoreApplication.translate("Interface", u"Print...", None))
        self.actionClose.setText(QCoreApplication.translate("Interface", u"Close", None))
        self.actionExit.setText(QCoreApplication.translate("Interface", u"Exit", None))
        self.actionUndo.setText(QCoreApplication.translate("Interface", u"Undo", None))
        self.actionCut.setText(QCoreApplication.translate("Interface", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("Interface", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("Interface", u"Paste", None))
        self.actionSelect.setText(QCoreApplication.translate("Interface", u"Select", None))
        self.actionSelect_All.setText(QCoreApplication.translate("Interface", u"Select All", None))
        self.actionTheme.setText(QCoreApplication.translate("Interface", u"Theme", None))
        self.actionZoom_in.setText(QCoreApplication.translate("Interface", u"Zoom in", None))
        self.actionZoom_out.setText(QCoreApplication.translate("Interface", u"Zoom out", None))
        self.actionFont.setText(QCoreApplication.translate("Interface", u"Font", None))
        self.actionPrefrences.setText(QCoreApplication.translate("Interface", u"Prefrences", None))
        self.actionAbout.setText(QCoreApplication.translate("Interface", u"About", None))
        self.actionDark_Light_Mode.setText(QCoreApplication.translate("Interface", u"Dark/Light Mode", None))
        ___qtablewidgetitem = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Interface", u"Source IP", None));
        ___qtablewidgetitem1 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Interface", u"sMAC", None));
        ___qtablewidgetitem2 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Interface", u"Source Port", None));
        ___qtablewidgetitem3 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Interface", u"Destenation IP", None));
        ___qtablewidgetitem4 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Interface", u"dMAC", None));
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(6)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Interface", u"BiDirBytes", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(7)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Interface", u"BiDirPackets", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(8)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Interface", u"Protocol", None));
        ___qtablewidgetitem8 = self.tableWidget_2.horizontalHeaderItem(9)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Interface", u"IP Version", None));
        ___qtablewidgetitem9 = self.tableWidget_2.horizontalHeaderItem(10)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Interface", u"Server", None));
        ___qtablewidgetitem10 = self.tableWidget_2.horizontalHeaderItem(11)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Interface", u"Application", None));
        ___qtablewidgetitem11 = self.tableWidget_2.horizontalHeaderItem(12)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Interface", u"Classification", None));

        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)

        self.BackButton_2.setText(QCoreApplication.translate("Interface", u"Back", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("Interface", u"Traffic Analysis ", None))
        ___qtablewidgetitem12 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Interface", u"sIP", None));
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Interface", u"dIP", None));
        ___qtablewidgetitem14 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Interface", u"Protocol", None));
        ___qtablewidgetitem15 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("Interface", u"IP Version", None));
        ___qtablewidgetitem16 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("Interface", u"Server", None));
        ___qtablewidgetitem17 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("Interface", u"Application", None));
        ___qtablewidgetitem18 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("Interface", u"Category", None));
        self.BackButton.setText(QCoreApplication.translate("Interface", u"Back", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Interface", u"Traffic Clasification", None))
        ___qtablewidgetitem19 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("Interface", u"sIP", None));
        ___qtablewidgetitem20 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("Interface", u"dIP", None));
        ___qtablewidgetitem21 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("Interface", u"Protocol", None));
        ___qtablewidgetitem22 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("Interface", u"IP Version", None));
        ___qtablewidgetitem23 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("Interface", u"Server", None));
        ___qtablewidgetitem24 = self.tableWidget_3.horizontalHeaderItem(5)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("Interface", u"Application", None));
        ___qtablewidgetitem25 = self.tableWidget_3.horizontalHeaderItem(6)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("Interface", u"Category", None));
        self.BackButton_3.setText(QCoreApplication.translate("Interface", u"Back", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Interface", u"System Visibility Mode", None))
        self.menuFile.setTitle(QCoreApplication.translate("Interface", u"File", None))
        self.menuSettings.setTitle(QCoreApplication.translate("Interface", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("Interface", u"Help", None))
        self.menuEdit.setTitle(QCoreApplication.translate("Interface", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("Interface", u"View", None))
    # retranslateUi

